# Jekyll Configuration
title: Mason Fox's Blog
description: From barn to server
author: Mason Fox
email: masonfox22@gmail.com
social:
  github: masonfox
  linkedin: masonfox
url: "https://masonfox.net"
baseurl: ""

# Google Analytics
google_analytics: G-2ZH5YFDHSG

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
highlighter: rouge

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - CLAUDE.md

# Include files
include:
  - .well-known

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      
# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll_picture_tag

# Jekyll Archives
jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag
  permalinks:
    tag: '/tags/:name/'

# Jekyll Picture Tag
picture:
  source: assets/images/